[tools]
node = "latest"
ruby = "latest"
go = "latest"
bun = "latest"
gleam = "latest"
erlang = "latest"
elixir = "latest"
lua = "5.1"
rust = "nightly"
zig = "latest"
java = "21"
pnpm = "latest"
kotlin = "latest"
"github:odin-lang/Odin" = "latest"
