[tools]
bun = "latest"
rust = "latest"
node = "latest"
ruby = "latest"
go = "latest"
erlang = "latest"
gleam = "latest"
elixir = "latest"
lua = "5.1"
"github:odin-lang/Odin" = "latest"
zig = "latest"
