# TokyoNight Alacritty Colors
# Default colors
[colors]
background = '#222436'
foreground = '#c8d3f5'

cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
light-black = '#444a73'
light-red = '#ff757f'
ight-green = '#c3e88d'
light-yellow = '#ffc777'
light-blue = '#82aaff'
light-magenta = '#c099ff'
light-cyan = '#86e1fc'
light-white = '#c8d3f5'



