# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x11131aff
bordercolor = 0x8c909fff
dropcolor = 0xadc6ff80
splitcolor = 0xf4aeffff
focuscolor = 0xadc6ffff
maximizescreencolor = 0xb1c6f7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xf4aeffff
globalcolor = 0x4d8efeff
overlaycolor = 0x344972ff
